# Generated by Django 4.0.4 on 2022-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='capacity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
