# Generated by Django 4.0.4 on 2022-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_alter_detail_capacity_alter_detail_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='opening',
            field=models.BooleanField(null=True),
        ),
    ]
